[workspace]
name = "ros2mcp"
version = "0.1.0"
description = "ROS2 MCP Server"
authors = ["Nicolas Gres <info@gres.io>"]
channels = ["robostack-jazzy", "conda-forge"]
platforms = ["linux-64", "win-64", "osx-arm64"]

[activation]
scripts = ["install/setup.bash"]
[target.win-64.activation]
scripts = ["install/setup.bat"]

[activation.env]
RMW_IMPLEMENTATION = "rmw_cyclonedds_cpp"

[tasks]
clean = "rm -rf install build log"
build = { cmd = "colcon build --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython3_FIND_VIRTUALENV=ONLY", inputs = [
    "src",
], outputs = [
    "install",
    "build",
] }
sim = "ros2 run turtlesim turtlesim_node"
start-tb4 = "ros2 launch nav2_bringup tb4_simulation_launch.py headless:=False"
mcp = { cmd = "ros2 run mcp_server mcp_server", depends-on = ["build"] }
demo-tb4 = { cmd = "bash -c 'source install/setup.bash && ros2 launch mcp_demo_node tb4.launch.py'", depends-on = [
    "build",
] }

[dependencies]
python = ">=3.12.0,<3.13"
ros-jazzy-desktop = "*"
ros-jazzy-turtlesim = "*"
ros-jazzy-ament-cmake-auto = "*"
ros-jazzy-nav2-bringup = "*"
compilers = "*"
pkg-config = "*"
cmake = "<4.0"
make = "*"
ninja = "*"
colcon-common-extensions = "*"
setuptools = "<=70.4"
mcp = "*"
anyio = "*"
starlette = "*"
uvicorn = "*"
numpy = "*"

[target.linux.dependencies]
libgl-devel = "*"
